apiVersion: v1
kind: Service
metadata:
  name: {{ include "slurm-emulator.fullname" . }}
  labels:
    {{- include "slurm-emulator.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "slurm-emulator.selectorLabels" . | nindent 4 }}
  ports:
    - name: control-api
      port: 8080
      targetPort: control-api
      protocol: TCP
    - name: slurmrestd
      port: 6820
      targetPort: slurmrestd
      protocol: TCP
    {{- if .Values.ssh.enabled }}
    - name: ssh
      port: {{ .Values.ssh.port }}
      targetPort: ssh
      protocol: TCP
    {{- end }}
